languageCode = "zh-cn"
languageName = "简体中文"
weight = 1
title = "云原生实验室"
contentDir = "content"

[params]
  displayName = "中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006年1月2日"
  logo = "img/logo.webp"
  # secondaryLogo = "PATH"
  description = "云原生实验室是一个关注容器、Kubernetes、Istio、DevOps、Prometheus、Envoy、Golang、云原生、微服务等技术的个人博客。"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "米开朗基杨"
  image = "img/avatar.png"
  headline = "云原生搬砖师 & [Sealos](https://sealos.run) 开发者布道师 & [FastGPT](https://github.com/labring/FastGPT) 熟练工"
  bio = "云原生搬砖师 & [Sealos](https://sealos.run) 开发者布道师 & [FastGPT](https://github.com/labring/FastGPT) 熟练工"
  links = [
    { rss = "/index.xml" },
    { x-twitter = "https://twitter.com/CarsonYangk8s" },
    { wechat = "https://jsd.onmicrosoft.cn/gh/yangchuansheng/imghosting5@main/uPic/tmpm1ykjt96.webp" },
    { github = "https://github.com/yangchuansheng" },
    { telegram = "https://t.me/cloudnativer" },
  ]

  