languageCode = "en"
languageName = "English"
weight = 1
title = "Cloud Native Labs"
disabled = false
contentDir = "content/en"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.webp"
  # secondaryLogo = "PATH"
  description = "Cloud Native Lab: A specialized blog diving into container technology, Kubernetes, Istio, DevOps practices, Prometheus monitoring, Envoy, Golang development, and trends in cloud-native architecture and microservices."
  # copyright = "Copy, _right?_ :thinking_face:"
  [params.article]
    editURL = "https://github.com/yangchuansheng/blog/tree/main/content/en"

  [[params.slideImages]]
    imgAddress = "https://socialify.git.ci/labring/sealos/image?description=1&descriptionEditable=a%20cloud%20operating%20system%20distribution%20based%20on%20the%20Kubernetes%20kernel.&font=Raleway&forks=1&logo=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Flabring%2Fsealos%40main%2Fdocs%2Fwebsite%2Fstatic%2Ficons%2Flogo.svg&name=1&owner=1&pattern=Brick%20Wall&stargazers=1&theme=Light"
    linkAddress = "https://github.com/labring/sealos"
    linkEvent = "Sealos"
  
  [[params.slideImages]]
    imgAddress = "https://socialify.git.ci/labring/fastgpt/image?description=1&descriptionEditable=a%20knowledge-based%20platform%20built%20on%20the%20LLM,%20offers%20out-of-the-box%20data%20processing%20and%20workflow%20orchestration%20through%20Flow%20visualization.&font=Raleway&forks=1&logo=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Flabring%2FFastGPT%40main%2F.github%2Fimgs%2Flogo.svg&name=1&pattern=Brick%20Wall&stargazers=1&theme=Light"
    linkAddress = "https://cloud.fastgpt.in/?inviterId=64215e9914d068bf840141d0"
    linkEvent = "FastGPT"
  
  [[params.slideImages]]
    imgAddress = "https://socialify.git.ci/labring/laf/image?description=1&descriptionEditable=Laf%20is%20a%20serverless%20platform%20integrating%20functions,%20databases%20and%20storage.%20Publish%20online%20anytime,%20anywhere.&font=Raleway&forks=1&logo=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Fyangchuansheng%2Fimghosting-test%40main%2FuPic%2F2023-11-13-11-33-rI41Bu.svg&name=1&pattern=Brick%20Wall&stargazers=1&theme=Light"
    linkAddress = "https://github.com/labring/laf"
    linkEvent = "Laf"

[author]
  name = "Carson Yang"
  image = "img/avatar.png"
  headline = "[Sealos](https://sealos.io) Community Pollinator, Cloud Native Lover ☸️, Blogger, GFW fucker..."
  bio = "[Sealos](https://sealos.io) Community Pollinator, Cloud Native Lover ☸️, Blogger, GFW fucker..."
  links = [
    { rss = "/index.xml" },
    { x-twitter = "https://twitter.com/CarsonYangk8s" },
    { wechat = "https://cdn.jsdelivr.net/gh/yangchuansheng/imghosting5@main/uPic/tmpm1ykjt96.webp" },
    { github = "https://github.com/yangchuansheng" },
    { telegram = "https://t.me/cloudnativer" },
  ]