name: github pages

on:
  workflow_dispatch:
  push:
    branches:
      - main # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.120.4"
          extended: true

      - name: replace cdn
        run: |
          sed -i "s/jsdelivr.icloudnative.io/cdn.jsdelivr.net/g" $(grep -rl "jsdelivr.icloudnative.io" ./)
          sed -i "s/jsd.onmicrosoft.cn/cdn.jsdelivr.net/g" $(grep -rl "jsd.onmicrosoft.cn" ./)
          sed -i "s#cdn.staticfile.org/Swiper/#cdn.jsdelivr.net/npm/swiper@#g" $(grep -rl "cdn\.staticfile\.org" ./)
          sed -i "s#cdn.staticfile.org/layer#cdnjs.cloudflare.com/ajax/libs/layer#g" $(grep -rl "cdn\.staticfile\.org" ./)

      - name: Build
        run: |
          hugo -v --gc --minify
          git clone https://github.com/yangchuansheng/envoy-handbook ../envoy-handbook
          cd ../envoy-handbook
          hugo -v --gc --minify -d ../blog/public/envoy-handbook

      - uses: actions/checkout@v4
        with:
          repository: "yangchuansheng/jstc"
          path: "public/jstc"

      - name: Clean
        run: |
          rm -rf public/jstc/.git*

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./public
